name: ipquery_dart
description: Dart SDK for ipquery.io API (IP geolocation and risk info)
version: 0.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  http: ^1.2.1
dev_dependencies:
  test: ^1.25.2
